In [1]:
import numpy as np
import pandas as pd
import h5py

In [2]:
training_file = "kaggle_data/X_train.h5/X_train.h5"
train_ds = h5py.File(training_file, mode='r')

OSError: Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')

In [4]:
list(train_ds.keys())

['eeg_1',
 'eeg_2',
 'eeg_3',
 'eeg_4',
 'eeg_5',
 'eeg_6',
 'eeg_7',
 'index',
 'index_absolute',
 'index_window',
 'pulse',
 'x',
 'y',
 'z']

In [11]:
train_ds['eeg_1'][1]

array([  -10.525451 ,   -11.4539385,    22.652863 , ..., -8920.934    ,
       -8358.432    , -7660.106    ], dtype=float32)

In [13]:
a, b = np.random.rand(2, 2), np.random.rand(2, 2)

In [15]:
a, b

(array([[0.13888178, 0.80390237],
        [0.95836762, 0.82616128]]),
 array([[0.41825778, 0.55426192],
        [0.91978963, 0.37841857]]))

In [18]:
a = np.cumsum(a)

In [20]:
z = np.array([[1, 2], [3, 4]])

In [23]:
np.linalg.norm(z, ord=2, axis=1)

array([2.23606798, 5.        ])

In [24]:
2.236**2

4.999696000000001